# Generated from terminal/palette.json.
set -g foundation_foreground dce2ea
set -g foundation_muted 8993a3
set -g foundation_accent 79b8d4
set -g foundation_error e08b92
set -g fish_color_normal dce2ea
set -g fish_color_command dce2ea
set -g fish_color_param dce2ea
set -g fish_color_comment 8993a3
set -g fish_color_autosuggestion 8993a3
set -g fish_color_error e08b92
set -g fish_color_quote 79b8d4
set -g fish_color_operator 79b8d4
set -g fish_color_escape 79b8d4
set -g fish_color_redirection 79b8d4
set -g fish_color_end 79b8d4
set -g fish_color_valid_path dce2ea
