# Generated from terminal/palette.json.
set -g foundation_foreground eef1f6
set -g foundation_muted 939eae
set -g foundation_accent 98ccf9
set -g foundation_error f1a5a5
set -g fish_color_normal eef1f6
set -g fish_color_command eef1f6
set -g fish_color_param eef1f6
set -g fish_color_comment 939eae
set -g fish_color_autosuggestion 939eae
set -g fish_color_error f1a5a5
set -g fish_color_quote 98ccf9
set -g fish_color_operator 98ccf9
set -g fish_color_escape 98ccf9
set -g fish_color_redirection 98ccf9
set -g fish_color_end 98ccf9
set -g fish_color_valid_path eef1f6
