#!/usr/bin/env python3
"""Journal config replacements before mutation; restore only owned paths."""
import argparse
import fcntl
import json
import os
from pathlib import Path
import re
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parent.parent
CONFIG = Path(os.environ.get('XDG_CONFIG_HOME', Path.home() / '.config'))
STATE = Path(os.environ.get('XDG_STATE_HOME', Path.home() / '.local/state')) / 'desktop-foundation'
DATA = Path(os.environ.get('XDG_DATA_HOME', Path.home() / '.local/share'))


def lua_string(value):
    return '"' + str(value).replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n') + '"'


def save(manifest):
    temporary = STATE / 'manifest.tmp'
    with temporary.open('w') as stream:
        stream.write(json.dumps(manifest, indent=2) + '\n')
        stream.flush()
        os.fsync(stream.fileno())
    temporary.replace(STATE / 'manifest.json')
    descriptor = os.open(STATE, os.O_DIRECTORY)
    try:
        os.fsync(descriptor)
    finally:
        os.close(descriptor)


def owned(entry):
    path = Path(entry['path'])
    return path.is_symlink() and os.readlink(path) == entry['source']


def fingerprint(path):
    if not (path.exists() or path.is_symlink()):
        return None
    stat = path.lstat()
    return [stat.st_dev, stat.st_ino, stat.st_mode]


def restore(manifest):
    for entry in manifest['entries']:
        path = Path(entry['path'])
        backup = Path(entry['backup']) if entry['backup'] else None
        if 'original' not in entry:
            entry['original'] = fingerprint(backup) if backup else None
        original_present = entry['original'] is not None and fingerprint(path) == entry['original']
        if fingerprint(path) is not None and not owned(entry) and not original_present:
            raise RuntimeError(f'Refusing to overwrite modified config: {path}')
        if original_present and backup and fingerprint(backup) is not None:
            raise RuntimeError(f'Ambiguous recovery: {path}')
    save(manifest)
    persistent_units = [Path(e['path']).name for e in manifest['entries']
                        if '/systemd/user/' in e['path'] and '/niri.service.wants/' not in e['path']
                        and Path(e['path']).name in {'desktop-foundation-wallpaper.service', 'desktop-foundation-clipboard-persist.service'}]
    if persistent_units:
        subprocess.run(['systemctl', '--user', 'stop', *persistent_units], check=True)
    for entry in reversed(manifest['entries'][:]):
        path = Path(entry['path'])
        backup = Path(entry['backup']) if entry['backup'] else None
        if owned(entry):
            path.unlink()
        if backup and fingerprint(backup) is not None:
            backup.rename(path)
        manifest['entries'].remove(entry)
        save(manifest)
    (STATE / 'manifest.json').unlink()
    subprocess.run(['systemctl', '--user', 'daemon-reload'], check=True)
    subprocess.run(['fc-cache', '-f'], check=True)
    print('Original configuration restored. Reload your active compositor if needed.')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('action', choices=['install', 'restore'])
    parser.add_argument('--profile', default='default')
    parser.add_argument('--compositor', choices=['niri', 'hyprland'], default='niri')
    args = parser.parse_args()
    STATE.mkdir(parents=True, exist_ok=True)
    with (STATE / 'lock').open('w') as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        manifest_path = STATE / 'manifest.json'
        manifest = json.loads(manifest_path.read_text()) if manifest_path.exists() else {'root': str(ROOT), 'entries': []}
        if manifest['root'] != str(ROOT):
            raise RuntimeError('A different checkout owns this installation; restore it first.')
        if args.action == 'restore':
            if manifest_path.exists():
                restore(manifest)
            else:
                print('Nothing deployed.')
            return
        if not re.fullmatch(r'[A-Za-z0-9_-]+', args.profile):
            raise RuntimeError('Invalid profile name')
        if not (ROOT / 'profiles' / args.profile).is_dir():
            print(f'Profile {args.profile} unavailable; using portable defaults.')
        if args.compositor == 'niri':
            from render_niri import render
            wrapper = render(ROOT, args.profile)
            with tempfile.NamedTemporaryFile(mode='w', suffix='.kdl') as candidate:
                candidate.write(wrapper)
                candidate.flush()
                subprocess.run(['niri', 'validate', '-c', candidate.name], check=True)
            source = STATE / 'niri.kdl'
            targets = [(CONFIG / 'niri/config.kdl', source), (CONFIG / 'quickshell/desktop-foundation', ROOT / 'shell')]
        else:
            wrapper = (f'-- Generated by desktop-foundation; edit repository files.\nFOUNDATION_ROOT = {lua_string(ROOT)}\n'
                       f'FOUNDATION_PROFILE = {lua_string(args.profile)}\n'
                       'dofile(FOUNDATION_ROOT .. "/compositor/hyprland/hyprland.lua")\n')
            with tempfile.NamedTemporaryFile(mode='w', suffix='.lua') as candidate:
                candidate.write(wrapper)
                candidate.flush()
                subprocess.run(['Hyprland', '--verify-config', '-c', candidate.name], check=True)
            source = STATE / 'hyprland.lua'
            targets = [(CONFIG / 'hypr/hyprland.lua', source), (CONFIG / 'quickshell/desktop-foundation', ROOT / 'shell')]
        if args.compositor == 'niri':
            from session_units import targets as session_targets
            targets.extend(session_targets(ROOT, CONFIG, STATE, DATA))
        # Fish owns writable universal variables outside the source checkout.
        fish_runtime = STATE / 'terminal/fish'
        fish_runtime.mkdir(parents=True, exist_ok=True)
        for child in (ROOT / 'terminal/fish').iterdir():
            link = fish_runtime / child.name
            if not link.exists() and not link.is_symlink():
                link.symlink_to(child)
        subprocess.run(['fish', '--no-config', '-n', str(ROOT / 'terminal/fish/config.fish')], check=True)
        targets.extend([(CONFIG / 'wireplumber/wireplumber.conf.d/60-desktop-foundation-bluetooth.conf', ROOT / 'audio/wireplumber/60-desktop-foundation-bluetooth.conf'),
                        (CONFIG / 'kitty', ROOT / 'terminal/kitty'),
                        (CONFIG / 'fish', fish_runtime),
                        (CONFIG / 'fastfetch', ROOT / 'terminal/fastfetch'),
                        (DATA / 'fonts/desktop-foundation', ROOT / 'fonts')])
        for path, src in targets:
            entries = [e for e in manifest['entries'] if e['path'] == str(path)]
            if entries and not owned(entries[0]):
                raise RuntimeError(f'Deployed path changed outside this script: {path}')
        temporary = source.with_suffix('.tmp')
        temporary.write_text(wrapper)
        temporary.replace(source)
        try:
            for path, src in targets:
                if any(e['path'] == str(path) for e in manifest['entries']):
                    continue
                path.parent.mkdir(parents=True, exist_ok=True)
                backup = None
                original = fingerprint(path)
                if original is not None:
                    backup = STATE / f'backup-{len(manifest["entries"])}'
                    if fingerprint(backup) is not None:
                        raise RuntimeError(f'Unexpected backup exists: {backup}')
                entry = {'path': str(path), 'source': str(src),
                         'backup': str(backup) if backup else None, 'original': original}
                manifest['entries'].append(entry)
                save(manifest)  # Write-ahead: SIGKILL after any following step is recoverable.
                if backup:
                    path.rename(backup)
                path.symlink_to(src)

        except Exception:
            restore(manifest)
            raise
        subprocess.run(['systemctl', '--user', 'daemon-reload'], check=True)
        subprocess.run(['fc-cache', '-f'], check=True)
        print(f'Deployed {args.compositor} profile {args.profile}; backups and manifest: {STATE}')
        print('No session restart performed. Config changes may auto-reload in the selected compositor.')


if __name__ == '__main__':
    main()
