#!/usr/bin/env python3
"""Back up and link exactly two config paths; restore only owned links."""
import argparse
import fcntl
import json
import os
from pathlib import Path
import re
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parent.parent
CONFIG = Path(os.environ.get('XDG_CONFIG_HOME', Path.home() / '.config'))
STATE = Path(os.environ.get('XDG_STATE_HOME', Path.home() / '.local/state')) / 'desktop-foundation'


def lua_string(value):
    return '"' + str(value).replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n') + '"'


def save(manifest):
    temporary = STATE / 'manifest.tmp'
    temporary.write_text(json.dumps(manifest, indent=2) + '\n')
    temporary.replace(STATE / 'manifest.json')


def owned(entry):
    path = Path(entry['path'])
    return path.is_symlink() and os.readlink(path) == entry['source']


def restore(manifest):
    for entry in manifest['entries']:
        path = Path(entry['path'])
        if (path.exists() or path.is_symlink()) and not owned(entry):
            raise RuntimeError(f'Refusing to overwrite modified config: {path}')
    for entry in reversed(manifest['entries']):
        path = Path(entry['path'])
        if path.exists() or path.is_symlink():
            if not owned(entry):
                raise RuntimeError(f'Refusing to overwrite modified config: {path}')
            path.unlink()
        if entry['backup']:
            Path(entry['backup']).rename(path)
        manifest['entries'].remove(entry)
        save(manifest)
    (STATE / 'manifest.json').unlink()
    print('Original configuration restored. Reload Hyprland if still in that session.')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('action', choices=['install', 'restore'])
    parser.add_argument('--profile', default='default')
    args = parser.parse_args()
    STATE.mkdir(parents=True, exist_ok=True)
    with (STATE / 'lock').open('w') as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        manifest_path = STATE / 'manifest.json'
        manifest = json.loads(manifest_path.read_text()) if manifest_path.exists() else {'root': str(ROOT), 'entries': []}
        if manifest['root'] != str(ROOT):
            raise RuntimeError('A different checkout owns this installation; restore it first.')
        if args.action == 'restore':
            if manifest_path.exists():
                restore(manifest)
            else:
                print('Nothing deployed.')
            return
        if not re.fullmatch(r'[A-Za-z0-9_-]+', args.profile):
            raise RuntimeError('Invalid profile name')
        for name in ['hardware', 'monitors', 'input']:
            if not (ROOT / 'profiles' / args.profile / f'{name}.lua').is_file():
                raise RuntimeError(f'Incomplete profile: {args.profile}')
        wrapper = (f'-- Generated by desktop-foundation; edit repository files.\nFOUNDATION_ROOT = {lua_string(ROOT)}\n'
                   f'FOUNDATION_PROFILE = {lua_string(args.profile)}\n'
                   'dofile(FOUNDATION_ROOT .. "/compositor/hyprland/hyprland.lua")\n')
        with tempfile.NamedTemporaryFile(mode='w', suffix='.lua') as candidate:
            candidate.write(wrapper)
            candidate.flush()
            subprocess.run(['Hyprland', '--verify-config', '-c', candidate.name], check=True)
        source = STATE / 'hyprland.lua'
        targets = [(CONFIG / 'hypr/hyprland.lua', source), (CONFIG / 'quickshell/desktop-foundation', ROOT / 'shell')]
        for path, src in targets:
            entries = [e for e in manifest['entries'] if e['path'] == str(path)]
            if entries and not owned(entries[0]):
                raise RuntimeError(f'Deployed path changed outside this script: {path}')
        source.write_text(wrapper)
        try:
            for path, src in targets:
                if any(e['path'] == str(path) for e in manifest['entries']):
                    continue
                path.parent.mkdir(parents=True, exist_ok=True)
                backup = None
                if path.exists() or path.is_symlink():
                    backup = STATE / f'backup-{len(manifest["entries"])}'
                    if backup.exists() or backup.is_symlink():
                        raise RuntimeError(f'Unexpected backup exists: {backup}')
                    path.rename(backup)
                entry = {'path': str(path), 'source': str(src), 'backup': str(backup) if backup else None}
                manifest['entries'].append(entry)
                save(manifest)
                path.symlink_to(src)
        except Exception:
            restore(manifest)
            raise
        print(f'Deployed profile {args.profile}; backups and manifest: {STATE}')
        print('No reload or session restart performed. Use hyprctl reload after review.')


if __name__ == '__main__':
    main()
