#!/usr/bin/env python3
"""Generate terminal colors from the single portable palette."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent


def render():
    terminal = ROOT / 'terminal'
    p = json.loads((terminal / 'palette.json').read_text())
    kitty = ['# Generated by scripts/render_terminal.py; edit terminal/palette.json.']
    for name, key in [('background', 'background'), ('foreground', 'foreground'),
                      ('cursor', 'accent'), ('selection_background', 'selection'),
                      ('selection_foreground', 'foreground'), ('url_color', 'accent')]:
        kitty.append(f'{name} #{p[key]}')
    kitty.extend(f'color{i} #{value}' for i, value in enumerate(p['ansi']))
    (terminal / 'kitty/colors.conf').write_text('\n'.join(kitty) + '\n')
    fish = ['# Generated from terminal/palette.json.']
    fish.extend(f'set -g foundation_{key} {p[key]}' for key in ['foreground', 'muted', 'accent', 'error'])
    fish.extend(f'set -g fish_color_{key} {p[value]}' for key, value in {
        'normal': 'foreground', 'command': 'foreground', 'param': 'foreground',
        'comment': 'muted', 'autosuggestion': 'muted', 'error': 'error',
        'quote': 'accent', 'operator': 'accent', 'escape': 'accent',
        'redirection': 'accent', 'end': 'accent', 'valid_path': 'foreground'}.items())
    (terminal / 'fish/theme.fish').write_text('\n'.join(fish) + '\n')
    config = json.loads((terminal / 'fastfetch/config.jsonc').read_text())
    rgb = ';'.join(str(int(p['accent'][i:i + 2], 16)) for i in (0, 2, 4))
    config['display']['color']['keys'] = '38;2;' + rgb
    config['logo']['color'] = {'1': '38;2;' + rgb, '2': '38;2;' + rgb}
    (terminal / 'fastfetch/config.jsonc').write_text(json.dumps(config, indent=2) + '\n')


if __name__ == '__main__':
    render()
